--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/davidgamingzz/Lootbox
build-by-default: true
branches:
- master
projects:
  Lootbox:
    path: ""
    icon: “icon.jpg
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 4.0
    lint:
      phpstan: false
...
